# -*- coding: utf-8 -*-
"""fibonacciseriespython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQYBnDuxGWgnr-idB4jZqSbwnd-X6JBI
"""

def fibonacci(n):
    fib_sequence = [0, 1]

    if n <= 0:
        return "Invalid input. Please enter a positive integer."
    elif n == 1:
        return [0]
    elif n == 2:
        return fib_sequence

    for i in range(2, n):
        next_fib = fib_sequence[-1] + fib_sequence[-2]
        fib_sequence.append(next_fib)

    return fib_sequence
n = int(input("Enter the number of Fibonacci numbers you want to generate: "))
fibonacci_sequence = fibonacci(n)
print(f"The first {n} Fibonacci numbers are: {fibonacci_sequence}")