# -*- coding: utf-8 -*-
"""setoperations.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bknydVvqE5XYUBGezidsfkHUJKQiYnyX
"""

def set_operations():
    # Define two sets
    E = {0, 2, 4, 6, 8}
    N = {1, 2, 3, 4, 5}

    # Perform set operations
    union_set = E | N  # Union of E and N
    intersection_set = E & N  # Intersection of E and N
    difference_set = E - N  # Difference of E and N (E - N)
    symmetric_diff_set = E ^ N  # Symmetric difference of E and N

    # Print the results
    print(f"Union of E and N is {union_set}")
    print(f"Intersection of E and N is {intersection_set}")
    print(f"Difference of E and N is {difference_set}")
    print(f"Symmetric difference of E and N is {symmetric_diff_set}")

# Call the function to execute the operations
set_operations()